apiVersion: v1
kind: Service
metadata:
  name: {{ include "motus.fullname" . }}
  labels:
    {{- include "motus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "motus.selectorLabels" . | nindent 4 }}
