name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use Google Cloud
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      env:
        GCR_REGISTRY: gcr.io/${{ secrets.GCP_PROJECT_ID }}
        IMAGE_NAME: motus-users-ms
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $GCR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG -t $GCR_REGISTRY/$IMAGE_NAME:latest ./app/motus-users-ms
        docker push $GCR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        docker push $GCR_REGISTRY/$IMAGE_NAME:latest

    #- name: Get GKE credentials
    #  run: |
    #    gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
    #      --zone ${{ secrets.GKE_ZONE }} \
    #      --project ${{ secrets.GCP_PROJECT_ID }}

    #- name: Update Kubernetes deployment
    #  run: |
    #    kubectl set image deployment/motus-users-ms motus-users-ms=$GCR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG