name: CD

#on:
#  push:
#    branches: [ main ]

on:
  workflow_run:
    workflows: ["CI"]  # name of your CI workflow file (from `name:` at the top of it)
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        install_components: 'gke-gcloud-auth-plugin'

    - name: Authenticate to Google Cloud
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        rm /tmp/gcp-key.json

    - name: Configure Docker to use Google Cloud
      run: |
        gcloud auth configure-docker europe-west8-docker.pkg.dev --quiet
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin europe-west8-docker.pkg.dev

    - name: Build and push Docker image
      env:
        GCR_REGISTRY: europe-west8-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/myreg
        IMAGE_NAME: motus-users-ms
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $GCR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG -t $GCR_REGISTRY/$IMAGE_NAME:latest ./app/motus-users-ms
        docker push $GCR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        docker push $GCR_REGISTRY/$IMAGE_NAME:latest

    #- name: Get GKE credentials
    #  run: |
    #    gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
    #      --zone ${{ secrets.GKE_ZONE }} \
    #      --project ${{ secrets.GCP_PROJECT_ID }}

    #- name: Update Kubernetes deployment
    #  run: |
    #    kubectl set image deployment/motus-users-ms motus-users-ms=$GCR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    