name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'app/motus-users-ms/.nvmrc'
        cache: 'yarn'
        cache-dependency-path: 'app/motus-users-ms/yarn.lock'

    - name: Install dependencies
      working-directory: app/motus-users-ms
      run: yarn install --frozen-lockfile

    #- name: Fix linting issues
    #  working-directory: app/motus-users-ms
    #  run: yarn fix

    #- name: Run linting
    #  working-directory: app/motus-users-ms
    #  run: yarn lint

    - name: Run tests
      working-directory: app/motus-users-ms
      run: yarn test

    - name: Build Docker image
      working-directory: app/motus-users-ms
      run: docker build -t motus-users-ms:${{ github.sha }} . 